name: Create Release

on:
  push:
    branches:
      - develop
      - master

permissions:
  contents: read
  pull-requests: write

jobs:
  create_release:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Extract Version from Tag or Branch
        id: extract_version
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/V-}
          else
            VERSION=${GITHUB_REF#refs/heads/}
          fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Version extracted: $VERSION"

      - name: Create Tag
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          tags: "V-${{ env.VERSION }}"

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "V-${{ env.VERSION }}"
          release_name: "Release V-${{ env.VERSION }}"
          body: ${{ steps.changelog.outputs.changelog }}
          draft: false
          prerelease: false
