name: Create Release

on:
  push:
    branches:
      - develop
      - staging
      - main
    tags:
      - 'V-*'

jobs:
  create_release:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Extract Version from Tag or Branch
        id: extract_version
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/V-}
          else
            VERSION=${GITHUB_REF#refs/heads/}
          fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Version extracted: $VERSION"

      - name: Create Tag
        uses: gittools/actions/git-tag@v1
        with:
          tag_name: "V-${{ env.VERSION }}"  # Utilise la version extraite
          git_user_name: "github-actions"
          git_user_email: "github-actions@github.com"

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "V-${{ env.VERSION }}"
          release_name: "Release V-${{ env.VERSION }}"
          body: ${{ steps.changelog.outputs.changelog }}
          draft: false
          prerelease: false
