name: Create Release

on:
  push:
    branches:
      - develop
      - master

permissions:
  contents: read
  pull-requests: write 

jobs:
  create_release:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      -   name: Push tag
          id: tag_version
          uses: mathieudutour/github-tag-action@v6.1
          with:
              commit_sha: ${{ github.event.pull_request.merge_commit_sha }}
              github_token: ${{ secrets.GITHUB_TOKEN }}
              custom_tag: ${{ steps.version.outputs.version }}

      -   name: Create (pre)release tag
          uses: ncipollo/release-action@v1
          with:
              generateReleaseNotes: true
              tag: ${{ steps.version.outputs.version }}